title: Numerius Engineering LLC
email: numerius.engineering@gmail.com
description: >-
  Consulting-led electronics product development across hardware, software,
  rapid prototyping, and application development.
baseurl: "/web"
url: "https://numerius-engineering.github.io"
permalink: pretty
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _drafts
  - _site

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
